# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$line_break\
$directory\
$fill\
$os\
$shell\
$cmd_duration\
\n$character"""

palette = "zeiss"
# Inserts a blank line between shell prompts
add_newline = false

[username]
format = '[$user ]($style)'
show_always = true
style_user = "main"
style_root = "bg:#9A348E"
disabled = false

[directory]
style = "path"
truncation_length = 3
truncation_symbol = 'â€¦/'

[fill]
symbol = ' '

[os]
format = '[$symbol ]($style)'
style = 'main'
disabled = false

[os.symbols]
Windows = "\uE62A"
Arch = "\uE732"
Ubuntu = "\uEf72"
Debian = "\uE77d"

[shell]
bash_indicator = "\uEBCA"
fish_indicator = "\uEE41"
powershell_indicator = "\uebc7"
unknown_indicator = 'mystery shell'
style = 'main'
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[cmd_duration]
format = '[$duration]($style)'
style = 'duration'
min_time = 0



# Define color palette from OhhMyPosh Zeiss terminal
[palettes.zeiss]
main = '#8D4DD3'
svn = '#ffeb3b'
duration = '#b8ff75'
path = '#61AFEF'
success = '#20A452'
error = '#e91e63'

