command_timeout = 200

format = """
$username\
$line_break\
$directory\
$fill\
$os\
$shell\
$cmd_duration\
\n$character"""

palette = "zeiss"
add_newline = false

[username]
format = '[$user ]($style)'
show_always = true
style_user = "main"
style_root = "bg:#9A348E"
disabled = false

[os]
format = '[$symbol ]($style)'
style = 'main'
disabled = false

[os.symbols]
Windows = "\uE62A"
Arch = "\uE732"
Ubuntu = "\uEf72"
Debian = "\uE77d"

[fill]
symbol = ' '

[shell]
bash_indicator = "\uebca"
fish_indicator = "\uEE41"
powershell_indicator = "\uebc7"
unknown_indicator = 'mystery shell'
style = 'main'
disabled = false

[character]
error_symbol = "[✗](red)"
success_symbol = "[❯❯ ](green)"
#style = 'main'

[directory]
style = "path"
truncation_length = 2
truncation_symbol = "\uEB06 .../"
home_symbol = "\uEB06 "
use_os_path_sep = true

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[cmd_duration]
format = '[$duration]($style)'
style = 'duration'
min_time = 0


# Define color palette from OhhMyPosh Zeiss terminal
[palettes.zeiss]
main = '#8D4DD3'
svn = '#ffeb3b'
duration = '#b8ff75'
path = '#61AFEF'
success = '#20A452'
error = '#E91E63'